title:             Jun-Hee
email:             junhee.heu_at_gmail.com
description:       Jun-Hee's blog
author:            Jun-Hee HEU
baseurl:           ""
url:               "http://junheeheu.github.io"

# Social Profiles
twitter_username:  
github_username:   junheeheu
facebook_username: junhee.heu

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
